name: BuilderTools
api: [3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12]
author: CzechPMDevs
authors: [VixikCZ]
version: 1.1.0-beta1
description: WorldEdit plugin
main: buildertools\BuilderTools

permissions:
  bt.cmd:
    default: op
    description: Permissions for all BuilderTools commands
    childern:
      bt.cmd.pos1:
        description: Permissions for //pos1
        default: op
      bt.cmd.pos2:
        description: Permissions for //pos2
        default: op
      bt.cmd.fill:
        descripion: Permissions for //fill
        default: op
      bt.cmd.wand:
        description: Permissions for //wand
        default: op
      bt.cmd.help:
        description: Permissions for //help
        default: op
      bt.cmd.sphere:
        description: Permissions for //sphere
        default: op
      bt.cmd.help:
        description: Permissions for //help
        default: op
      bt.cmd.draw:
        description: Permissions for //draw
        default: op
      bt.cmd.ip:
        description: Permissions for //id
        default: op
      bt.cmd.clearinventory:
        description: Permissions for //clearinventory
        default: op
      bt.cmd.naturalize:
        description: Permissions for //naturalize
        default: op
      bt.cmd.copy:
        description: Permissions for //copy
        default: op
      bt.cmd.paste:
        description: Permissions for //paste
        default: op
